version: 2

project_name: wt

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/wt
    binary: wt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - shell/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: default-anton
    name: wt

brews:
  - repository:
      owner: default-anton
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/default-anton/wt"
    description: "Git worktree manager"
    license: "MIT"
    install: |
      bin.install "wt"

      # Install shell-init (wrapper function) + completions combined
      (bash_completion/"wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "bash") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "bash")
      (zsh_completion/"_wt").write Utils.safe_popen_read(bin/"wt", "shell-init", "zsh") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "zsh")
      (fish_completion/"wt.fish").write Utils.safe_popen_read(bin/"wt", "shell-init", "fish") + "\n" + Utils.safe_popen_read(bin/"wt", "completion", "fish")
