version: 2

project_name: wt

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/wt
    binary: wt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - shell/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: default-anton
    name: wt

brews:
  - repository:
      owner: default-anton
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/default-anton/wt"
    description: "Git worktree manager"
    license: "MIT"
    install: |
      bin.install "wt"
      bash_completion.install "shell/wt.bash" => "wt"
      zsh_completion.install "shell/wt.zsh" => "_wt"
      fish_completion.install "shell/wt.fish" => "wt.fish"
